[IO_Slot_Cfg]
Plat_Type = CPHMC_1A ;平台类型
Dev_Type = HVDC ;控保主机
Cfg_Ver = V1.0.0.1 ;配置文件版本号

;启动核心配置
[BOOT_CFG]
;0：启动app镜像，1：启动调试镜像；2：不启动，
Core0  = 0 ; R5F0
Core1  = 0 ; R5F1
Core2  = 0 ; R5F2
Core3  = 0 ; R5F3
Core4  = 0 ; DSPC6X0
Core5  = 0 ; DSPC6X1
Core6  = 0 ; DSPC7X0
Core7  = 0 ; A72

[CheckCode]
CHECKSUM = 0xC3322388